### PR TITLE
Adde a config option to change the y offset of the menu

### PR DESCRIPTION
**Pull request by GreenTeaSeb**
The menu was clipping by bottom panel so I added an configuration option to be able to change the offset from the bottom.

### CODE REVIEW

**Comment by GreenTeaSeb** [comment]
Just forgot to remove the tools folder, my bad on that one.

**Comment by SnoutBug** [comment]
I would much rather get to the root of the issue, considering other launchers don't have this problem

**Comment by GreenTeaSeb** [comment]
Well, one of  the things I found was that you were adding instead of subtracting the bottom panel.

**Comment by SnoutBug** [comment]
That how screen corrdinates work (the origin is top left instead of bottom left)

I've created issue #6 to discuss this further

**Pull request closed without merging**
